In [16]:
from jupyter_bioacoustic import JupyterAudio

---

# ANNOTATE

Annotation workflow: assign species and mark time/frequency regions

In [17]:
ja_annotate = JupyterAudio(
    data_path='data/annotate-data.csv',
    config='config/annotate-simple.yaml',
    output='outputs/annotate-output.csv',
    annotator_name='brookie',
    annotate_date=20260421,
    inline=True)
ja_annotate.open()

In [31]:
ja_annotate.source.head()

,id,common_name,scientific_name,confidence,rank,start_time,end_time,audio_path,county,lat,lon
0,1,Wrentit,Chamaea fasciata,0.600,1,6469.55,6481.55,audio/test2.flac,El Dorado,38.86290,-120.98969
1,2,Dog barks,NaN,0.369,1,11431.89,11443.89,NaN,San Bernardino,34.53716,-115.02921
2,3,Sooty grouse,Dendragapus fuliginosus,0.643,3,757.46,769.46,NaN,Santa Barbara,34.42366,-120.58807
3,4,Sooty grouse,Dendragapus fuliginosus,0.843,2,1712.92,1724.92,NaN,Mono,38.13757,-117.89407
4,5,Downy woodpecker call,Dryobates pubescens,0.425,1,13806.95,13818.95,NaN,Sacramento,38.26908,-121.81004

In [32]:
ja_annotate.output()

,common_name,start_time,end_time,min_freq,max_freq,annotator_name,annotate_date
0,Canada goose,757.46,769.46,NaN,NaN,brookie,20260421
1,Hermit thrush,1712.92,1724.92,NaN,NaN,brookie,20260421

---

# REVIEW

Simple review workflow: confirm or reject model predictions

In [33]:
ja_review = JupyterAudio(
    data='data/review-data.csv',
    config='config/review-simple.yaml',
    output='outputs/review-output.csv',
    reviewer_name='brookie',
    review_date=20260414,
    inline=True)
ja_review.open()

In [59]:
ja_review.output()

,detection_id,is_valid,notes,verified_common_name,reviewer_name,review_date
0,1,yes,NaN,NaN,brookie,20260414
1,2,yes,NaN,NaN,brookie,20260414
2,3,yes,NaN,NaN,brookie,20260414
3,4,no,NaN,Northern saw-whet owl,brookie,20260414
4,5,yes,NaN,NaN,brookie,20260414
5,6,no,NaN,Wolf howl,brookie,20260414
6,7,yes,Bioacoustics is cool,NaN,brookie,20260414
7,8,no,NaN,Great horned owl,brookie,20260414